# docker-compose.yml
version: "3"
services:
    app:
        build: .
        depends_on:
            - postgres
        ports:
            - "9010:3000"

    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: petition
