# docker-compose.yml
version: "3"
services:
    app:
        build: .
        volumes:
            - .:/opt/beeDocker/
            - /opt/beeDocker/node_modules
        depends_on:
            - postgres
        ports:
            - "9010:8080"

    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: petition
