# docker-compose.yml
version: "3"
services:
    db:
        image: postgres:alpine
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: petition

    app:
        image: beetition:latest
        restart: always
        ports:
            - "9010:8080"
        volumes:
            - petition:/opt/beeDocker/
        depends_on:
            - db

volumes:
    db:
    petition:
